### ISSUE TITLE
pb.cpp compiling issue

### ISSUE THREAD

**Issue by WT215** [fuchslab/scModels#14]
Hi,

In am interested in Poisson Beta function like "cpp_qpb", so I would like to compile the file pb.cpp individually but failed.

Would you mind being more specific about how to install your package? I am under Windows 10 environment. I followed your instruction for installing mpfr but failed.

Thanks a lot!

Best,
Wenhao

**Comment by hkumar6** [comment]
@WT215 This package is meant to be compiled using R, and RStudio is the best way to go about it. So you should install RStudio and set the `LIB_MPFR` environment in Windows. Then, you can install this package in RStudio by this command: `install.packages("scModels")`.

**Comment by WT215** [comment]
Now `> install.packages("scModels")` works!

Thank  you very much!

**Comment by WT215** [comment]
By the way, may I also ask whether the density function of Poisson Beta you provided "dpb" is as the same as the `dBP` provided here: [https://github.com/sandberg-lab/txburst/blob/master/Figure%201a.ipynb](url) (located at `In [5]:`)

Thanks a lot!

**Comment by WT215** [comment]
They seem to be the same, thanks!
