### ISSUE TITLE
Fails to compile with recent mpfr

### ISSUE THREAD

**Issue by Enchufa2** [fuchslab/scModels#15]
The `mpreal.h` header needs to be fixed, because apparently it's mixing definitions of macros and functions (see [this thread](https://stackoverflow.com/questions/67756873/why-does-gcc-misinterpret-this-macro)). These are the kind of errors I get on Fedora 34 with mpfr v4.1.0:

```
In file included from mpreal.h:121,
                 from shared.h:4,
                 from gillespie.cpp:3:
mpreal.h: In copy constructor 'mpfr::mpreal::mpreal(const mpfr::mpreal&)':
mpreal.h:582:27: error: no matching function for call to 'mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)'
  582 |     mpfr_init2(mpfr_ptr(),mpfr_get_prec(u.mpfr_srcptr()));
      |                           ^~~~~~~~~~~~~
```

Complete log [here](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-34-x86_64/02317425-R-CRAN-scModels/builder-live.log.gz).

**Comment by hkumar6** [comment]
Thanks for the issue report.
I tested the package on OSX using `mpfr v4.1.0` installed by Homebrew, with the latest `mpreal.h` and I got no errors. So I will try on Fedora 34 to see if the error can be reproduced.
Meanwhile, I will update the package with the new `mpreal v3.6.8`.

**Comment by Enchufa2** [comment]
v4.1.0 on OSX may not have some patches from upstream mpfr that are applied on Fedora. With these in place, the package fails consistently in Fedora 33, 34 and rawhide.

**Comment by hkumar6** [comment]
I pushed changes to the `mpfr_update` branch. Could you please check if it works now?

**Comment by Enchufa2** [comment]
Checked. The `mpfr_update` branch works fine.
